# Generated by Django 5.1.6 on 2026-02-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='availabilityblock',
            new_name='listings_av_listing_1378a6_idx',
            old_name='listings_av_listing_a0165e_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_status_b16def_idx',
            old_name='listings_li_status_9eb9b7_idx',
        ),
        migrations.RenameIndex(
            model_name='listing',
            new_name='listings_li_locatio_df6c0f_gist',
            old_name='listings_li_locatio_06d84d_gist',
        ),
    ]
