# Generated by Django 5.1.6 on 2026-02-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listings_av_listing_a0165e_idx_listings_av_listing_1378a6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='listings/photos/'),
        ),
    ]
