# Generated by Django 5.1.6 on 2026-02-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_listing_fdd061_idx',
            old_name='reservations_listing_458139_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_host_id_2f984d_idx',
            old_name='reservations_host_id_0a09d2_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_guest_i_854290_idx',
            old_name='reservations_guest_i_a66f1c_idx',
        ),
    ]
